# Saneesh
# date: Oct 01, 2023

#Install the required packages
# install.packages('googlesheets4')
# install.packages('dplyr')
# install.packages('ggplot2')


#Load the required libraries 
library(googlesheets4)
library(dplyr)
library(ggplot2)

# copy link to required sheet
test <- read_sheet('https://docs.google.com/spreadsheets/d/1_gcL26IGkkvAaFPcDwHkqEpQ9bpz_LlTBBg7pmn7Kvo/edit#gid=0')

# or
# copy the sheet ID
test1 <- read_sheet('1_gcL26IGkkvAaFPcDwHkqEpQ9bpz_LlTBBg7pmn7Kvo')

# give permission when the browser opens
# back to RStudio

View(test)

View(test1)

test3 <- test %>% select(Name, Sex, District, Crop, `Yield (kg)`, `Rate (Rs)`)
names(test3)

# yield comparison 
test3 %>%
  group_by(District, Crop) %>%
  summarise(Total_Yield = sum(`Yield (kg)`)) %>%
  ggplot(aes(x = Crop, y = Total_Yield, fill = District)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title = "Yield comparison by District", 
       x = "Crop", y = "Total Yield")

# income generated by sexes
data <- test3 %>%
  mutate(Income = `Yeild (kg)` * `Rate (Rs)`)

income_by_sex <- data %>%
  group_by(Sex, Crop) %>%
  summarise(Total_Income = sum(Income))

ggplot(income_by_sex, aes(x = Crop, y = Total_Income, fill = Sex)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title = "Income comparison by Sex", 
       x = "Crop", y = "Total Income (Rs)") +
  theme_minimal()



#check if ggplot2 is installed
system.file(package='ggplot2')


library(ggplot2)
ggplot(mtcars, aes(x=mpg, y=wt)) + 
  geom_point() +
  ggtitle("Test Plot: MPG vs Weight")



